version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo installing source npm dependencies...
      - npm install
  build:
    commands:
      - echo building...
      - npm run build
      - echo testing...
      - npm test -- --watchAll=false
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
